"""Trove-only environment loading for the dashboard process.

The dashboard is a standalone user service: unlike the gateway (which
injects the profile's ``.env`` into its own process every turn) it
receives *no* Hermes env wiring at all. The capture/identity vars it
needs — ``TROVE_PEOPLE`` (author-label resolution), ``TROVE_DB`` (DB
path override) — therefore live in a **trove-only env file**
(``.env.trove``):

- Generated by ``deploy/setup.sh`` from the profile's ``.env`` at setup
  time (only the ``TROVE_*`` keys are copied, so no ``SIGNAL_*``
  exposure to the dashboard process).
- Referenced by the systemd unit via
  ``EnvironmentFile=<profile>/.env.trove`` (see
  ``deploy/systemd/trove-dashboard.service``).

The loader here exists so a manual ``trove dashboard`` run picks the
file up without the unit: it is dotenv-format, but is read by a tiny
dependency-free parser (trove's only runtime deps are fastapi +
uvicorn) with strict semantics:

- A variable **already present in the process environment is never
  overwritten** (explicit env wins over the file, the standard dotenv
  rule — and it makes the loader safe to call more than once).
- Lines are ``KEY=VALUE``; ``export KEY=VALUE`` is accepted. Blank
  lines and ``#`` comments are ignored. Unquoted values: a `` #``
  (whitespace + hash) starts an inline comment. Quoted values
 (single or double) have their surrounding quotes removed.
- Missing file is not an error (the default ``~/.hermes/trove.db`` and
  unset ``TROVE_PEOPLE`` are both valid — the dashboard just shows no
  labels).
"""

import os
import re
from pathlib import Path

ENV_FILE_NAME = ".env.trove"

_LINE_RE = re.compile(
    r"""^\s*
        (?:export\s+)?                # optional `export ` prefix
        ([A-Za-z_][A-Za-z0-9_]*)      # key
        \s*=\s*
        (.*)$                         # raw value (parsed below)
    """,
    re.VERBOSE,
)


def _parse_value(raw: str) -> str:
    """Parse a dotenv value: strip quotes or the inline comment.

    Args:
        raw: The raw value text after ``KEY=`` (trailing whitespace
            already stripped).

    Returns:
        The parsed value string.
    """
    if not raw:
        return ""
    if raw[0] in ("'", '"') and len(raw) >= 2 and raw[-1] == raw[0]:
        # Quoted: surrounding quotes removed.
        return raw[1:-1]
    # Unquoted: an inline comment starts at the first whitespace-# pair.
    match = re.search(r"\s+#", raw)
    if match:
        raw = raw[: match.start()]
    return raw.strip()


def parse_trove_env_file(text: str) -> dict:
    """Parse dotenv-format text into a dict (no env mutation).

    Args:
        text: File contents.

    Returns:
        Dict of ``KEY -> value``; keys in file order, last occurrence
        wins (dotenv semantics). Malformed lines are skipped silently.
    """
    values = {}
    for line in text.splitlines():
        match = _LINE_RE.match(line)
        if not match:
            continue
        key, raw_value = match.group(1), match.group(2).rstrip()
        values[key] = _parse_value(raw_value)
    return values


def load_trove_env_file(path=None) -> Path | None:
    """Load a trove-only env file into the process environment.

    Resolution: the given ``path`` if set (``~`` expanded), else a
    search for ``.env.trove`` starting in the cwd and walking up to the
    filesystem root (mirrors the repo-local ``.env`` convention — a
    manual ``trove dashboard`` run from the deploy checkout finds the
    file that the systemd unit would have loaded).

    Args:
        path: Explicit path to a ``.env.trove`` (optional).

    Returns:
        The ``Path`` that was loaded, or ``None`` if no file was found.
    """
    if path is None:
        path = find_trove_env_file()
    else:
        path = Path(os.path.expanduser(str(path)))
    if path is None or not path.is_file():
        return None

    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None

    for key, value in parse_trove_env_file(text).items():
        # Never override a variable already in the process environment.
        if key in os.environ:
            continue
        os.environ[key] = value
    return path


def find_trove_env_file() -> Path | None:
    """Walk up from the cwd looking for ``.env.trove``.

    Returns:
        The first ``.env.trove`` found (cwd first), or ``None``.
    """
    current = Path.cwd()
    for directory in (current, *current.parents):
        candidate = directory / ENV_FILE_NAME
        if candidate.is_file():
            return candidate
    return None
